import Link from "next/link";
import "./globals.css";
// import { Sour_Gummy } from "next/font/google";

// export const gummy = Sour_Gummy({
//   weight: "200",
//   subsets: ["latin"],
//   display: "swap",
// });

export const metadata = {
  title: "Rating System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="flex flex-col min-h-screen relative pb-20">
      <body>
        <nav className="m-5">
          <Link
            href="/brand"
            className="border border-solid border-blue p-2 text-xl hover:bg-blue hover:text-brown rounded-xl"
          >
            All Brand
          </Link>
        </nav>
        {children}

        <footer className=" m-4 mt-auto absolute bottom-0 w-screen flex justify-center items-center text-center">
          <p className="w-full mx-auto max-w-screen-xl p-4 ">
            {" "}
            © 2024 Angelica™ . All Rights Reserved.
          </p>
        </footer>
      </body>
    </html>
  );
}
